name: AmanCraftPlugin
main: org.vandine.ken.amancraft.AmanCraftPlugin
version: ${version}
commands:
  pos:
    description: Displays your position or teleports you to another.
    usage: "Usage: '/pos' to get current position, or '/pos x y z' to teleport to x,y,z"
  hideme:
    description: Hides you from another player.
    usage: "Usage: '/hideme [player]'"
  showme:
    description: Reveal yourself to another player.
    usage: "Usage: '/showme [player]'"
  debug:
    description: Toggles your debugging status for this plugin.
    usage: /debug
